// Copyright 2026 tyler-blaine-hall. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPipelinePromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyDebugSaveNum int
	var bodyErrorFilePath string
	var bodyModel string
	var bodyOutputDir string
	var bodyOutputRepoDir string
	var bodyPaperFormat string
	var bodyPaperName string
	var bodyPdfJsonPath string
	var bodyPdfLatexPath string
	var bodyResume bool
	var bodyRunAnalyzing bool
	var bodyRunCoding bool
	var bodyRunDebugging bool
	var bodyRunPlanning bool

	cmd := &cobra.Command{
		Use:         "pipeline",
		Short:       "Starts the PaperCoder pipeline in the background and returns the run ID.",
		Long:        "Shortcut for 'pipeline run-endpoint-run-post'. Starts the PaperCoder pipeline in the background and returns the run ID.",
		Example:     "  paper2code-pp-cli pipeline --output-dir example-value",
		Annotations: map[string]string{"pp:endpoint": "pipeline.run-endpoint-run-post", "pp:method": "POST", "pp:path": "/pipeline/run"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("output-dir") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "output-dir")
			}
			if !cmd.Flags().Changed("output-repo-dir") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "output-repo-dir")
			}
			if !cmd.Flags().Changed("paper-name") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "paper-name")
			}
			if !cmd.Flags().Changed("pdf-json-path") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "pdf-json-path")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/pipeline/run"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyDebugSaveNum != 0 {
				body["debug_save_num"] = bodyDebugSaveNum
			}
			if bodyErrorFilePath != "" {
				body["error_file_path"] = bodyErrorFilePath
			}
			if bodyModel != "" {
				body["model"] = bodyModel
			}
			if bodyOutputDir != "" {
				body["output_dir"] = bodyOutputDir
			}
			if bodyOutputRepoDir != "" {
				body["output_repo_dir"] = bodyOutputRepoDir
			}
			if bodyPaperFormat != "" {
				body["paper_format"] = bodyPaperFormat
			}
			if bodyPaperName != "" {
				body["paper_name"] = bodyPaperName
			}
			if bodyPdfJsonPath != "" {
				body["pdf_json_path"] = bodyPdfJsonPath
			}
			if bodyPdfLatexPath != "" {
				body["pdf_latex_path"] = bodyPdfLatexPath
			}
			if cmd.Flags().Changed("resume") {
				body["resume"] = bodyResume
			}
			if cmd.Flags().Changed("run-analyzing") {
				body["run_analyzing"] = bodyRunAnalyzing
			}
			if cmd.Flags().Changed("run-coding") {
				body["run_coding"] = bodyRunCoding
			}
			if cmd.Flags().Changed("run-debugging") {
				body["run_debugging"] = bodyRunDebugging
			}
			if cmd.Flags().Changed("run-planning") {
				body["run_planning"] = bodyRunPlanning
			}
			data, _, err := c.PostWithParams(path, params, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyDebugSaveNum, "debug-save-num", 1, "Backups index for debugging.")
	cmd.Flags().StringVar(&bodyErrorFilePath, "error-file-path", "", "Path to error message file for debugging.")
	cmd.Flags().StringVar(&bodyModel, "model", "", "Model override (e.g. MiniMax-M2.7).")
	cmd.Flags().StringVar(&bodyOutputDir, "output-dir", "", "Directory to save generated artifacts.")
	cmd.Flags().StringVar(&bodyOutputRepoDir, "output-repo-dir", "", "Directory to save final output repository.")
	cmd.Flags().StringVar(&bodyPaperFormat, "paper-format", "JSON", "Input paper format.")
	cmd.Flags().StringVar(&bodyPaperName, "paper-name", "", "Name of the paper.")
	cmd.Flags().StringVar(&bodyPdfJsonPath, "pdf-json-path", "", "Path to the PDF-based JSON format.")
	cmd.Flags().StringVar(&bodyPdfLatexPath, "pdf-latex-path", "", "Path to LaTeX source files if paper-format is LaTeX.")
	cmd.Flags().BoolVar(&bodyResume, "resume", false, "Resume from an interrupted or failed run.")
	cmd.Flags().BoolVar(&bodyRunAnalyzing, "run-analyzing", true, "Execute analyzing stage.")
	cmd.Flags().BoolVar(&bodyRunCoding, "run-coding", true, "Execute coding stage.")
	cmd.Flags().BoolVar(&bodyRunDebugging, "run-debugging", false, "Execute debugging stage.")
	cmd.Flags().BoolVar(&bodyRunPlanning, "run-planning", true, "Execute planning stage.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
