// Copyright 2026 tyler-blaine-hall. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPdfPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyGptVersion string
	var bodyInputJsonPath string
	var bodyMode string
	var bodyOutputJsonPath string
	var bodyPaperName string

	cmd := &cobra.Command{
		Use:         "pdf",
		Short:       "Processes PDF input into clean, structured S2ORC JSON.",
		Long:        "Shortcut for 'pdf process-process-post'. Processes PDF input into clean, structured S2ORC JSON.",
		Example:     "  paper2code-pp-cli pdf --input-json-path example-value",
		Annotations: map[string]string{"pp:endpoint": "pdf.process-process-post", "pp:method": "POST", "pp:path": "/pdf/process"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("input-json-path") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "input-json-path")
			}
			if !cmd.Flags().Changed("output-json-path") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "output-json-path")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/pdf/process"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyGptVersion != "" {
				body["gpt_version"] = bodyGptVersion
			}
			if bodyInputJsonPath != "" {
				body["input_json_path"] = bodyInputJsonPath
			}
			if bodyMode != "" {
				body["mode"] = bodyMode
			}
			if bodyOutputJsonPath != "" {
				body["output_json_path"] = bodyOutputJsonPath
			}
			if bodyPaperName != "" {
				body["paper_name"] = bodyPaperName
			}
			data, _, err := c.PostWithParams(path, params, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyGptVersion, "gpt-version", "", "VLM model choice override.")
	cmd.Flags().StringVar(&bodyInputJsonPath, "input-json-path", "", "Path to input PDF or Grobid JSON.")
	cmd.Flags().StringVar(&bodyMode, "mode", "auto", "Processing mode: auto, vlm, olmocr, local.")
	cmd.Flags().StringVar(&bodyOutputJsonPath, "output-json-path", "", "Path to save processed and cleaned JSON.")
	cmd.Flags().StringVar(&bodyPaperName, "paper-name", "", "Name of the paper.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
