// Copyright 2026 tyler-blaine-hall. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRunsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:    "runs",
		Short:  "Manage runs",
		Hidden: true,
		RunE:   parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRunsDetailIdGetCmd(flags))
	cmd.AddCommand(newRunsListGetCmd(flags))
	return cmd
}
