// Copyright 2026 tyler-blaine-hall. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"paper2code-pp-cli/internal/cli"
	"paper2code-pp-cli/internal/client"
	"paper2code-pp-cli/internal/config"
	"paper2code-pp-cli/internal/mcp/cobratree"
	"paper2code-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("eval_run-evaluation-run-post",
			mcplib.WithDescription("Runs programmatic reference-free/reference-based evaluation on the generated repo. Required: eval_result_dir, output_dir, paper_name, pdf_json_path, target_repo_dir. Optional: data_dir (default: ../data), eval_type (default: ref_free), generated_n (default: 8) (plus 3 more). Returns the new EvalRunResponse."),
			mcplib.WithString("data_dir", mcplib.Description("Data directory path.")),
			mcplib.WithString("eval_result_dir", mcplib.Required(), mcplib.Description("Directory to save evaluation results.")),
			mcplib.WithString("eval_type", mcplib.Description("Evaluation type.")),
			mcplib.WithNumber("generated_n", mcplib.Description("Number of evaluation samples to average.")),
			mcplib.WithString("gold_repo_dir", mcplib.Description("Official gold repository directory.")),
			mcplib.WithString("gpt_version", mcplib.Description("Model choice override.")),
			mcplib.WithString("output_dir", mcplib.Required(), mcplib.Description("Artifact directory of the pipeline.")),
			mcplib.WithString("paper_name", mcplib.Required(), mcplib.Description("Name of the paper.")),
			mcplib.WithBoolean("papercoder", mcplib.Description("Evaluate as PaperCoder generated repo.")),
			mcplib.WithString("pdf_json_path", mcplib.Required(), mcplib.Description("Path to the PDF-based JSON.")),
			mcplib.WithString("target_repo_dir", mcplib.Required(), mcplib.Description("Generated repository directory.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/eval/run", false, nil, []mcpParamBinding{{PublicName: "data_dir", WireName: "data_dir", Location: "body"}, {PublicName: "eval_result_dir", WireName: "eval_result_dir", Location: "body"}, {PublicName: "eval_type", WireName: "eval_type", Location: "body"}, {PublicName: "generated_n", WireName: "generated_n", Location: "body"}, {PublicName: "gold_repo_dir", WireName: "gold_repo_dir", Location: "body"}, {PublicName: "gpt_version", WireName: "gpt_version", Location: "body"}, {PublicName: "output_dir", WireName: "output_dir", Location: "body"}, {PublicName: "paper_name", WireName: "paper_name", Location: "body"}, {PublicName: "papercoder", WireName: "papercoder", Location: "body"}, {PublicName: "pdf_json_path", WireName: "pdf_json_path", Location: "body"}, {PublicName: "target_repo_dir", WireName: "target_repo_dir", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("paper2code-enhanced-server-health_check-get",
			mcplib.WithDescription("Health Check. Returns the HealthResponse."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/health", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("pdf_process-process-post",
			mcplib.WithDescription("Processes PDF input into clean, structured S2ORC JSON. Required: input_json_path, output_json_path. Optional: gpt_version, mode (default: auto), paper_name. Returns the new PdfprocessResponse."),
			mcplib.WithString("gpt_version", mcplib.Description("VLM model choice override.")),
			mcplib.WithString("input_json_path", mcplib.Required(), mcplib.Description("Path to input PDF or Grobid JSON.")),
			mcplib.WithString("mode", mcplib.Description("Processing mode: auto, vlm, olmocr, local.")),
			mcplib.WithString("output_json_path", mcplib.Required(), mcplib.Description("Path to save processed and cleaned JSON.")),
			mcplib.WithString("paper_name", mcplib.Description("Name of the paper.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/pdf/process", false, nil, []mcpParamBinding{{PublicName: "gpt_version", WireName: "gpt_version", Location: "body"}, {PublicName: "input_json_path", WireName: "input_json_path", Location: "body"}, {PublicName: "mode", WireName: "mode", Location: "body"}, {PublicName: "output_json_path", WireName: "output_json_path", Location: "body"}, {PublicName: "paper_name", WireName: "paper_name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("pipeline_run-endpoint-run-post",
			mcplib.WithDescription("Starts the PaperCoder pipeline in the background and returns the run ID. Required: output_dir, output_repo_dir, paper_name, pdf_json_path. Optional: debug_save_num (default: 1), error_file_path, model (plus 7 more)."),
			mcplib.WithNumber("debug_save_num", mcplib.Description("Backups index for debugging.")),
			mcplib.WithString("error_file_path", mcplib.Description("Path to error message file for debugging.")),
			mcplib.WithString("model", mcplib.Description("Model override (e.g. MiniMax-M2.7).")),
			mcplib.WithString("output_dir", mcplib.Required(), mcplib.Description("Directory to save generated artifacts.")),
			mcplib.WithString("output_repo_dir", mcplib.Required(), mcplib.Description("Directory to save final output repository.")),
			mcplib.WithString("paper_format", mcplib.Description("Input paper format.")),
			mcplib.WithString("paper_name", mcplib.Required(), mcplib.Description("Name of the paper.")),
			mcplib.WithString("pdf_json_path", mcplib.Required(), mcplib.Description("Path to the PDF-based JSON format.")),
			mcplib.WithString("pdf_latex_path", mcplib.Description("Path to LaTeX source files if paper-format is LaTeX.")),
			mcplib.WithBoolean("resume", mcplib.Description("Resume from an interrupted or failed run.")),
			mcplib.WithBoolean("run_analyzing", mcplib.Description("Execute analyzing stage.")),
			mcplib.WithBoolean("run_coding", mcplib.Description("Execute coding stage.")),
			mcplib.WithBoolean("run_debugging", mcplib.Description("Execute debugging stage.")),
			mcplib.WithBoolean("run_planning", mcplib.Description("Execute planning stage.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/pipeline/run", false, nil, []mcpParamBinding{{PublicName: "debug_save_num", WireName: "debug_save_num", Location: "body"}, {PublicName: "error_file_path", WireName: "error_file_path", Location: "body"}, {PublicName: "model", WireName: "model", Location: "body"}, {PublicName: "output_dir", WireName: "output_dir", Location: "body"}, {PublicName: "output_repo_dir", WireName: "output_repo_dir", Location: "body"}, {PublicName: "paper_format", WireName: "paper_format", Location: "body"}, {PublicName: "paper_name", WireName: "paper_name", Location: "body"}, {PublicName: "pdf_json_path", WireName: "pdf_json_path", Location: "body"}, {PublicName: "pdf_latex_path", WireName: "pdf_latex_path", Location: "body"}, {PublicName: "resume", WireName: "resume", Location: "body"}, {PublicName: "run_analyzing", WireName: "run_analyzing", Location: "body"}, {PublicName: "run_coding", WireName: "run_coding", Location: "body"}, {PublicName: "run_debugging", WireName: "run_debugging", Location: "body"}, {PublicName: "run_planning", WireName: "run_planning", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("runs_detail-id-get",
			mcplib.WithDescription("Queries full status details and stage steps for a specific run ID. Required: run_id. Returns the RunDetailResponse."),
			mcplib.WithNumber("run_id", mcplib.Required(), mcplib.Description("Run id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/runs/{run_id}", false, nil, []mcpParamBinding{{PublicName: "run_id", WireName: "run_id", Location: "path"}}, []string{"run_id"}),
	)
	s.AddTool(
		mcplib.NewTool("runs_list-get",
			mcplib.WithDescription("Queries all run records from the SQLite database. Returns array of RunListItem."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/runs", false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("stats_aggregate-get",
			mcplib.WithDescription("Calculates global performance convergence rates, costs, and token consumption aggregates. Returns the StatsResponse."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/stats", false, nil, []mcpParamBinding{}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(path, params, headers)
				break
			}
			data, err = c.Get(path, params)
		case "POST":
			if len(headers) > 0 {
				data, _, err = c.PostWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PostWithParams(path, params, bodyArgs)
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'paper2code-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'paper2code-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "paper2code-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "paper2code-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "paper2code",
		"description": "Local API backend for executing and auditing PaperCoder's academic code generation pipeline.",
		"archetype":   "infrastructure",
		"tool_count":  7,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion paper2code-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name":        "eval",
				"description": "Manage eval",
				"endpoints":   []string{"run-evaluation-run-post"},
				"searchable":  true,
			},
			{
				"name":        "paper2code-enhanced-server-health",
				"description": "Manage paper2code enhanced server health",
				"endpoints":   []string{"check-get"},
				"syncable":    true,
			},
			{
				"name":        "pdf",
				"description": "Manage pdf",
				"endpoints":   []string{"process-process-post"},
				"searchable":  true,
			},
			{
				"name":        "pipeline",
				"description": "Manage pipeline",
				"endpoints":   []string{"run-endpoint-run-post"},
				"searchable":  true,
			},
			{
				"name":        "runs",
				"description": "Manage runs",
				"endpoints":   []string{"detail-id-get", "list-get"},
				"syncable":    true,
			},
			{
				"name":        "stats",
				"description": "Manage stats",
				"endpoints":   []string{"aggregate-get"},
				"syncable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
