// Copyright 2026 tyler-blaine-hall. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type EvalRunRequest struct {
	DataDir       string `json:"data_dir"`
	EvalResultDir string `json:"eval_result_dir"`
	EvalType      string `json:"eval_type"`
	GeneratedN    int    `json:"generated_n"`
	GoldRepoDir   string `json:"gold_repo_dir"`
	GptVersion    string `json:"gpt_version"`
	OutputDir     string `json:"output_dir"`
	PaperName     string `json:"paper_name"`
	Papercoder    bool   `json:"papercoder"`
	PdfJsonPath   string `json:"pdf_json_path"`
	TargetRepoDir string `json:"target_repo_dir"`
}

type EvalRunResponse struct {
	EvalType     string  `json:"eval_type"`
	OutputFile   string  `json:"output_file"`
	PaperName    string  `json:"paper_name"`
	Score        float64 `json:"score"`
	Status       string  `json:"status"`
	ValidSamples string  `json:"valid_samples"`
}

type HTTPValidationError struct {
	Detail json.RawMessage `json:"detail"`
}

type HealthResponse struct {
	DbAvailable bool   `json:"db_available"`
	DbPath      string `json:"db_path"`
	Status      string `json:"status"`
}

type PDFProcessRequest struct {
	GptVersion     string `json:"gpt_version"`
	InputJsonPath  string `json:"input_json_path"`
	Mode           string `json:"mode"`
	OutputJsonPath string `json:"output_json_path"`
	PaperName      string `json:"paper_name"`
}

type PDFProcessResponse struct {
	Message        string `json:"message"`
	OutputJsonPath string `json:"output_json_path"`
	Status         string `json:"status"`
}

type PipelineRunRequest struct {
	DebugSaveNum  int    `json:"debug_save_num"`
	ErrorFilePath string `json:"error_file_path"`
	Model         string `json:"model"`
	OutputDir     string `json:"output_dir"`
	OutputRepoDir string `json:"output_repo_dir"`
	PaperFormat   string `json:"paper_format"`
	PaperName     string `json:"paper_name"`
	PdfJsonPath   string `json:"pdf_json_path"`
	PdfLatexPath  string `json:"pdf_latex_path"`
	Resume        bool   `json:"resume"`
	RunAnalyzing  bool   `json:"run_analyzing"`
	RunCoding     bool   `json:"run_coding"`
	RunDebugging  bool   `json:"run_debugging"`
	RunPlanning   bool   `json:"run_planning"`
}

type PipelineRunResponse struct {
	Message   string `json:"message"`
	PaperName string `json:"paper_name"`
	RunId     int    `json:"run_id"`
	Status    string `json:"status"`
}

type RunDetailResponse struct {
	CompletedAt    string          `json:"completed_at"`
	ExecutorType   string          `json:"executor_type"`
	ModelUsed      string          `json:"model_used"`
	Notes          string          `json:"notes"`
	OutputDir      string          `json:"output_dir"`
	PaperName      string          `json:"paper_name"`
	RunId          int             `json:"run_id"`
	Stages         json.RawMessage `json:"stages"`
	StartedAt      string          `json:"started_at"`
	Status         string          `json:"status"`
	TotalCost      float64         `json:"total_cost"`
	TotalTokensIn  int             `json:"total_tokens_in"`
	TotalTokensOut int             `json:"total_tokens_out"`
	Trials         json.RawMessage `json:"trials"`
}

type RunListItem struct {
	CompletedAt string  `json:"completed_at"`
	Id          int     `json:"id"`
	ModelUsed   string  `json:"model_used"`
	PaperName   string  `json:"paper_name"`
	StartedAt   string  `json:"started_at"`
	Status      string  `json:"status"`
	TotalCost   float64 `json:"total_cost"`
}

type RunStageSummary struct {
	CostUsd   float64 `json:"cost_usd"`
	CreatedAt string  `json:"created_at"`
	StageName string  `json:"stage_name"`
	Success   bool    `json:"success"`
	TokensIn  int     `json:"tokens_in"`
	TokensOut int     `json:"tokens_out"`
}

type RunTrialSummary struct {
	AttemptNum     int     `json:"attempt_num"`
	CreatedAt      string  `json:"created_at"`
	ElapsedSeconds float64 `json:"elapsed_seconds"`
	Returncode     string  `json:"returncode"`
	Success        bool    `json:"success"`
}

type StatsResponse struct {
	CompletedRuns        int     `json:"completed_runs"`
	DebugConvergenceRate string  `json:"debug_convergence_rate"`
	FailedRuns           int     `json:"failed_runs"`
	RunningRuns          int     `json:"running_runs"`
	TotalCostUsd         float64 `json:"total_cost_usd"`
	TotalRuns            int     `json:"total_runs"`
	TotalTokensIn        int     `json:"total_tokens_in"`
	TotalTokensOut       int     `json:"total_tokens_out"`
	TotalTrials          int     `json:"total_trials"`
}

type ValidationError struct {
	Ctx   json.RawMessage `json:"ctx"`
	Input string          `json:"input"`
	Loc   json.RawMessage `json:"loc"`
	Msg   string          `json:"msg"`
	Type  string          `json:"type"`
}
